"""
VibeVision Dining - Dish Mention + Sentiment Extractor
=======================================================
Scans the Yelp Open Dataset, extracts dish mentions per restaurant, and
classifies each mention sentence with the trained sentiment model to
produce positive/neutral/negative counts per dish.

Output: dish_mentions_by_business.json
  {
    "<normalized_name>|<normalized_city>": [
      { "dish": "Pizza", "positive": 14, "neutral": 3, "negative": 1 },
      ...
    ],
    ...
  }

  Key format: lowercase alphanumeric+spaces, pipe-separated name and city.

Sentiment model priority:
  1. sentiment_model.pkl + vectorizer.pkl  (full sklearn model, generated by
     train_sentiment_model.py — highest accuracy)
  2. sentiment_model_minimal.json          (500-feature logistic regression
     shipped with the app — works without running training first)

Run:
    python extract_dish_mentions.py

Optional env vars:
    YELP_MAX_REVIEWS  - max reviews to scan (default 500000)
    TOP_DISHES        - max dishes per restaurant (default 6)
"""

import json
import os
import re
from collections import defaultdict

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_DIR       = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
DATASET_DIR    = os.path.join(BASE_DIR, 'Dataset')
BUSINESS_PATH  = os.path.join(DATASET_DIR, 'yelp_academic_dataset_business.json')
REVIEW_PATH    = os.path.join(DATASET_DIR, 'yelp_academic_dataset_review.json')
ML_DIR         = os.path.dirname(__file__)
OUTPUT_PATH    = os.path.join(ML_DIR, 'dish_mentions_by_business.json')
PKL_MODEL      = os.path.join(ML_DIR, 'sentiment_model.pkl')
PKL_VECTORIZER = os.path.join(ML_DIR, 'vectorizer.pkl')
MINIMAL_JSON   = os.path.join(ML_DIR, 'sentiment_model_minimal.json')

MAX_REVIEWS = int(os.environ.get('YELP_MAX_REVIEWS', '500000'))
TOP_DISHES  = int(os.environ.get('TOP_DISHES', '6'))

# ---------------------------------------------------------------------------
# Sentiment model loader
# ---------------------------------------------------------------------------

class SentimentClassifier:
    """Unified wrapper — uses sklearn pkl if present, else minimal JSON."""

    def __init__(self):
        if os.path.exists(PKL_MODEL) and os.path.exists(PKL_VECTORIZER):
            import pickle
            with open(PKL_MODEL, 'rb') as f:
                self._model = pickle.load(f)
            with open(PKL_VECTORIZER, 'rb') as f:
                self._vec = pickle.load(f)
            self._mode = 'sklearn'
            print("  Sentiment: using full sklearn pkl model.")
        elif os.path.exists(MINIMAL_JSON):
            with open(MINIMAL_JSON, 'r') as f:
                data = json.load(f)
            self._classes   = data['classes']          # ['negative','neutral','positive']
            self._features  = data['top_features']
            self._feat_idx  = {w: i for i, w in enumerate(self._features)}
            self._coef      = data['coef']             # shape (n_classes, n_features)
            self._intercept = data['intercept']
            self._mode = 'minimal'
            print("  Sentiment: using minimal JSON model (500 features).")
        else:
            self._mode = 'none'
            print("  WARNING: no sentiment model found — all mentions default to positive.")

    def predict(self, text: str) -> str:
        """Return 'positive', 'neutral', or 'negative'."""
        if self._mode == 'none':
            return 'positive'
        if self._mode == 'sklearn':
            return str(self._model.predict(self._vec.transform([text]))[0])
        # Minimal JSON inference: unigrams + bigrams matched against top_features
        tokens = re.sub(r'[^a-z\s]', ' ', text.lower()).split()
        ngrams = tokens + [f"{tokens[i]} {tokens[i+1]}" for i in range(len(tokens) - 1)]
        scores = list(self._intercept)
        for ng in ngrams:
            idx = self._feat_idx.get(ng)
            if idx is not None:
                for cls_i, coef_row in enumerate(self._coef):
                    scores[cls_i] += coef_row[idx]
        return self._classes[scores.index(max(scores))]


def sentences_containing(text: str, keyword: str) -> list[str]:
    """Split text into sentences and return those mentioning keyword."""
    parts = re.split(r'(?<=[.!?])\s+', text)
    kw_lower = keyword.lower()
    return [s for s in parts if kw_lower in s.lower()]


# ---------------------------------------------------------------------------
# Keyword vocabulary  (mirrors cuisineSpecificKeywords in RestaurantApiService.kt)
# ---------------------------------------------------------------------------
CUISINE_KEYWORDS: dict[str, set[str]] = {
    'japanese': {
        'ramen', 'sushi', 'sashimi', 'udon', 'tempura', 'gyoza', 'tonkatsu',
        'edamame', 'miso', 'yakitori', 'donburi', 'onigiri', 'takoyaki',
    },
    'mexican': {
        'taco', 'burrito', 'enchilada', 'quesadilla', 'tamale', 'pozole',
        'mole', 'carnitas', 'guacamole', 'nachos', 'chilaquiles', 'tostada',
    },
    'italian': {
        'pizza', 'pasta', 'risotto', 'lasagna', 'gnocchi', 'tiramisu',
        'bruschetta', 'carbonara', 'bolognese', 'ravioli', 'focaccia', 'cannoli',
    },
    'chinese': {
        'dumpling', 'dimsum', 'wonton', 'fried rice', 'lo mein', 'kung pao',
        'mapo tofu', 'peking duck', 'congee', 'char siu', 'bao', 'hot pot',
        'chow mein', 'spring roll', 'egg roll',
    },
    'indian': {
        'curry', 'naan', 'biryani', 'tikka masala', 'dal', 'samosa',
        'tandoori', 'palak paneer', 'chana masala', 'korma', 'vindaloo',
        'raita', 'lassi', 'gulab jamun',
    },
    'thai': {
        'pad thai', 'green curry', 'red curry', 'tom yum', 'som tum',
        'massaman', 'satay', 'larb', 'khao pad', 'mango sticky rice',
    },
    'american': {
        'burger', 'steak', 'ribs', 'wings', 'fries', 'brisket', 'pulled pork',
        'mac and cheese', 'fried chicken', 'biscuit', 'gravy', 'coleslaw',
        'chili', 'clam chowder', 'lobster roll',
    },
    'mediterranean': {
        'falafel', 'shawarma', 'kebab', 'hummus', 'pita', 'gyro', 'tabbouleh',
        'fattoush', 'baklava', 'moussaka', 'tzatziki',
    },
    'korean': {
        'bibimbap', 'bulgogi', 'kimchi', 'japchae', 'tteokbokki', 'galbi',
        'doenjang jjigae', 'sundubu', 'pajeon', 'kimbap',
    },
    'vietnamese': {
        'pho', 'banh mi', 'bun bo hue', 'goi cuon', 'com tam', 'bun cha',
        'ca phe', 'banh xeo', 'che', 'hu tieu',
    },
    'bar': {
        'wings', 'nachos', 'sliders', 'fries', 'burger', 'pretzel',
        'flatbread', 'tacos', 'quesadilla',
    },
}

# Generic fallback used for any cuisine not in the map above
GENERIC_FOOD_KEYWORDS: set[str] = {
    'pizza', 'pasta', 'burger', 'taco', 'burrito', 'ramen', 'sushi', 'sandwich',
    'salad', 'steak', 'fries', 'wings', 'noodles', 'dumplings', 'curry', 'pho',
    'risotto', 'paella', 'falafel', 'shawarma', 'kebab', 'gyoza', 'tempura',
    'ceviche', 'lasagna', 'brisket', 'ribs', 'nachos', 'quesadilla', 'omelet',
    'pancakes', 'waffles', 'chowder', 'soup', 'tiramisu', 'cheesecake',
    'fried chicken', 'fish and chips', 'bibimbap', 'bulgogi', 'banh mi',
    'pad thai', 'green curry', 'dim sum', 'spring roll', 'egg roll', 'bao',
    'croissant', 'waffle', 'crepe', 'quiche', 'souvlaki', 'hummus', 'pita',
    'gyro', 'empanada', 'arepa', 'jerk chicken', 'oxtail', 'plantain',
    'lobster roll', 'clam chowder', 'po boy', 'gumbo', 'jambalaya',
}

ALL_KEYWORDS = GENERIC_FOOD_KEYWORDS.copy()
for kw_set in CUISINE_KEYWORDS.values():
    ALL_KEYWORDS.update(kw_set)


def cuisine_keywords_for(category_str: str) -> set[str]:
    cat = (category_str or '').lower()
    matched: set[str] = set()
    for key, kws in CUISINE_KEYWORDS.items():
        if key in cat:
            matched.update(kws)
    return matched if matched else GENERIC_FOOD_KEYWORDS


def extract_dishes(text: str, vocab: set[str]) -> list[str]:
    """Return all keyword hits found in text (multi-word keywords handled)."""
    lower = text.lower()
    return [kw for kw in vocab if re.search(r'\b' + re.escape(kw) + r'\b', lower)]


def normalize_key(name: str, city: str) -> str:
    def clean(s: str) -> str:
        return re.sub(r'[^a-z0-9 ]', '', s.lower()).strip()
    return f"{clean(name)}|{clean(city)}"


# ---------------------------------------------------------------------------
# Step 1 – collect restaurant business_ids and their cuisine strings
# ---------------------------------------------------------------------------
print("Step 1/4 – scanning businesses …")
# business_id -> (name, city, categories)
restaurant_info: dict[str, tuple[str, str, str]] = {}

with open(BUSINESS_PATH, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        biz = json.loads(line)
        cats = (biz.get('categories') or '')
        if 'restaurant' in cats.lower():
            bid  = biz.get('business_id')
            name = (biz.get('name') or '').strip()
            city = (biz.get('city') or '').strip()
            if bid and name:
                restaurant_info[bid] = (name, city, cats)

print(f"  Found {len(restaurant_info):,} restaurant businesses.")

# ---------------------------------------------------------------------------
# Step 2 – load sentiment model
# ---------------------------------------------------------------------------
print("Step 2/4 – loading sentiment model …")
clf = SentimentClassifier()

# ---------------------------------------------------------------------------
# Step 3 – scan reviews, extract dish mentions and classify each sentence
# ---------------------------------------------------------------------------
print(f"Step 3/4 – scanning up to {MAX_REVIEWS:,} reviews …")

# { business_id: { dish: { 'positive': N, 'neutral': N, 'negative': N } } }
dish_sentiment: dict[str, dict[str, dict[str, int]]] = \
    defaultdict(lambda: defaultdict(lambda: {'positive': 0, 'neutral': 0, 'negative': 0}))


scanned = 0
with open(REVIEW_PATH, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        review = json.loads(line)
        bid = review.get('business_id')
        if bid not in restaurant_info:
            continue

        text = (review.get('text') or '').strip()
        if not text:
            continue

        vocab = cuisine_keywords_for(restaurant_info[bid][2])
        for dish in extract_dishes(text, vocab):
            for sent in sentences_containing(text, dish):
                label = clf.predict(sent)
                dish_sentiment[bid][dish][label] += 1

        scanned += 1
        if scanned % 50000 == 0:
            print(f"  … {scanned:,} reviews processed, "
                  f"{len(dish_sentiment):,} restaurants with dish data so far")
        if scanned >= MAX_REVIEWS:
            break

print(f"  Processed {scanned:,} reviews across {len(dish_sentiment):,} restaurants.")

# ---------------------------------------------------------------------------
# Step 4 – build output: top-N dishes ranked by sentiment score
# ---------------------------------------------------------------------------
print(f"Step 4/4 – writing output (top {TOP_DISHES} dishes per restaurant) …")

output: dict[str, list[dict]] = {}
for bid, dishes in dish_sentiment.items():
    info = restaurant_info.get(bid)
    if not info:
        continue
    name, city, _ = info
    key = normalize_key(name, city)

    # Rank by (positive - negative), then by total mentions as tiebreak
    ranked = sorted(
        dishes.items(),
        key=lambda x: (
            x[1]['positive'] - x[1]['negative'],
            x[1]['positive'] + x[1]['neutral'] + x[1]['negative'],
        ),
        reverse=True,
    )[:TOP_DISHES]

    if ranked:
        output[key] = [
            {
                'dish':     dish.title(),
                'positive': counts['positive'],
                'neutral':  counts['neutral'],
                'negative': counts['negative'],
            }
            for dish, counts in ranked
        ]

with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
    json.dump(output, f, indent=2)

print(f"\nDone. {len(output):,} restaurants written to:")
print(f"  {OUTPUT_PATH}")
print("\nNext step: copy to Android assets —")
print("  Copy-Item ml_pipeline\\dish_mentions_by_business.json "
      "android\\assets\\dish_mentions_by_business.json")

